import { useEffect, useState } from 'react';
import { getTeachers, getTeacher, getSubjects, getClasses, getClass, getBranches, getBranch, getPreference, savePreference, getDashboard } from '../service.js';

function useData(load, key = 'initial') { const [state,set]=useState({loading:true,data:null,error:null}); useEffect(()=>{let alive=true; set({loading:true,data:null,error:null}); load().then((data)=>alive&&set({loading:false,data,error:null})).catch((e)=>alive&&set({loading:false,data:null,error:e.message})); return()=>{alive=false};},[key]); return state; }
const Link=({to,children})=><a href={to}>{children}</a>;
function State({state,children}) { if(state.loading)return <p className="tkb-empty">Đang tải dữ liệu…</p>; if(state.error)return <p className="tkb-error" role="alert">{state.error}</p>; return children; }
const Badge=({active})=><span className="tkb-badge">{active ? 'Active' : 'Inactive'}</span>;

export function TeachersPage(){const s=useData(getTeachers);const [q,setQ]=useState('');const [active,setActive]=useState('all');return <Page title="Giáo viên"><State state={s}>{(()=>{const rows=(s.data?.teachers??[]).filter(t=>(active==='all'||String(t.isActive)===active)&&`${t.name} ${t.homeBranchName??''} ${t.specializations.map(x=>x.name).join(' ')}`.toLowerCase().includes(q.toLowerCase()));return <><Filters q={q} setQ={setQ} active={active} setActive={setActive}/><Table heads={['Giáo viên','Chuyên môn','Phân hiệu chính','Workload','Môn có thể dạy','Nguyện vọng']} rows={rows.map(t=><tr key={t.id}><td><Link to={`/teachers/${t.id}`}>{t.name}</Link><br/><Badge active={t.isActive}/></td><td>{t.specializations.map(x=>x.name).join(', ')||'—'}</td><td>{t.homeBranchName??'—'}</td><td>{t.workload.teaching??t.workload.standard??'—'}</td><td>{t.specializations.length}</td><td>{labelSession(t.preference.preferredSession)}</td></tr>)}/></>})()}</State></Page>}
export function TeacherPage({id}){const s=useData(()=>getTeacher(id));return <Page title="Chi tiết giáo viên"><State state={s}>{s.data&&<><p><Link to={`/teacher-preferences?teacher=${id}`}>Chỉnh nguyện vọng</Link></p><Info rows={[['Tên',s.data.teacher.name],['Email',s.data.teacher.email||'—'],['Điện thoại',s.data.teacher.phone||'—'],['Phân hiệu',s.data.teacher.homeBranchName||'—'],['Trạng thái',s.data.teacher.isActive?'Active':'Inactive'],['Workload',s.data.teacher.workload.teaching??s.data.teacher.workload.standard??'—'],['Ca ưu tiên',labelSession(s.data.teacher.preference.preferredSession)]]}/><h2>Chuyên môn</h2><Table heads={['Môn học','ID']} rows={s.data.teacher.specializations.map(x=><tr key={x.id}><td>{x.name}</td><td className="tkb-mono">{x.id}</td></tr>)}/></>}</State></Page>}
export function SubjectsPage(){const s=useData(getSubjects);return <Page title="Môn học"><State state={s}><Table heads={['Mã','Tên','Trạng thái']} rows={(s.data?.subjects??[]).map(x=><tr key={x.id}><td>{x.code||'—'}</td><td>{x.name}</td><td><Badge active={x.isActive}/></td></tr>)}/></State></Page>}
export function ClassesPage(){const s=useData(getClasses);const [q,setQ]=useState('');return <Page title="Lớp"><State state={s}><input className="tkb-search" placeholder="Tìm tên lớp" value={q} onChange={e=>setQ(e.target.value)}/><Table heads={['Lớp','Khối','Môn / tiết mỗi tuần','Trạng thái']} rows={(s.data?.classes??[]).filter(x=>x.name.toLowerCase().includes(q.toLowerCase())).map(x=><tr key={x.id}><td><Link to={`/classes/${x.id}`}>{x.name}</Link></td><td>{x.block?.name??'—'}</td><td>{x.curriculum.map(c=>`${c.subject?.name??'—'} (${c.periodsPerWeek})`).join(', ')||'—'}</td><td><Badge active={x.isActive}/></td></tr>)}/></State></Page>}
export function ClassPage({id}){const s=useData(()=>getClass(id));return <Page title="Curriculum lớp"><State state={s}>{s.data&&<><Info rows={[['Lớp',s.data.class.name],['Khối',s.data.class.block],['Trạng thái',s.data.class.isActive?'Active':'Inactive']]}/><Table heads={['Môn','Số tiết / tuần','Năm học']} rows={s.data.class.curriculum.map(x=><tr key={x.id}><td>{x.subject?.name??'—'}</td><td>{x.periodsPerWeek}</td><td>{x.academicYear??'—'}</td></tr>)}/></>}</State></Page>}
export function BranchesPage(){const s=useData(getBranches);return <Page title="Phân hiệu"><State state={s}><Table heads={['Mã','Tên','Trạng thái','Số lớp','Giáo viên home']} rows={(s.data?.branches??[]).map(x=><tr key={x.id}><td>{x.code}</td><td><Link to={`/branches/${x.id}`}>{x.name}</Link></td><td><Badge active={x.isActive}/></td><td>{x.classCount}</td><td>{x.homeTeacherCount}</td></tr>)}/></State></Page>}
export function BranchPage({id}){const s=useData(()=>getBranch(id));return <Page title="Chi tiết phân hiệu"><State state={s}>{s.data&&<><h2>{s.data.branch.name}</h2><h3>Lớp</h3><p>{s.data.branch.classes.map(x=>x.name).join(', ')||'—'}</p><h3>Giáo viên home</h3><p>{s.data.branch.teachers.map(x=><span key={x.id}><Link to={`/teachers/${x.id}`}>{x.name}</Link>{' · '}</span>)||'—'}</p></>}</State></Page>}
export function PreferencesPage(){const params=new URLSearchParams(location.search);const initial=params.get('teacher')||'';const t=useData(getTeachers);const [id,setId]=useState(initial);const p=useData(()=>id?getPreference(id):Promise.resolve(null));const [session,setSession]=useState('both');const [dirty,setDirty]=useState(false);const [notice,setNotice]=useState('');useEffect(()=>{if(p.data){setSession(p.data.preference.preferredSession??'both');setDirty(false)}},[p.data]);useEffect(()=>{const leave=e=>{if(dirty){e.preventDefault();e.returnValue='';}};addEventListener('beforeunload',leave);return()=>removeEventListener('beforeunload',leave)},[dirty]);async function save(){try{await savePreference(id,{preferredSession:session});setDirty(false);setNotice('Đã lưu nguyện vọng. Lần tạo TKB tiếp theo sẽ dùng giá trị này.')}catch(e){setNotice(e.message)}}return <Page title="Nguyện vọng giáo viên"><State state={t}><label className="tkb-control"><span>Giáo viên</span><select value={id} onChange={e=>{setId(e.target.value);setNotice('')}}><option value="">Chọn giáo viên…</option>{(t.data?.teachers??[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></State>{id&&<State state={p}><section className="tkb-controls"><label className="tkb-control"><span>Ca ưu tiên</span><select value={session} onChange={e=>{setSession(e.target.value);setDirty(true)}}><option value="morning">Sáng</option><option value="afternoon">Chiều</option><option value="both">Cả hai</option></select></label><button className="tkb-generate" onClick={save}>Lưu</button><button onClick={()=>{setSession(p.data?.preference.preferredSession??'both');setDirty(false)}}>Hủy</button></section>{notice&&<p className={notice.startsWith('Đã')?'tkb-notice':'tkb-error'}>{notice}</p>}<p className="tkb-hint">Chỉ hiện trường preference mà scheduling model hiện hỗ trợ. Ca ưu tiên là soft preference; solver vẫn quyết định tính khả thi.</p></State>}</Page>}
export function DashboardPage(){const s=useData(getDashboard);return <Page title="Tổng quan"><State state={s}>{s.data&&<div className="tkb-stats">{Object.entries(s.data.counts).map(([k,v])=><div key={k}><strong>{v}</strong><span>{({branches:'Phân hiệu',classes:'Lớp',activeTeachers:'Giáo viên active',activeSubjects:'Môn active',assignments:'Assignment',requiredPeriods:'Tiết cần xếp'})[k]}</span></div>)}</div>}</State></Page>}
function Page({title,children}){return <div className="tkb-page"><header className="tkb-page-head"><h1>{title}</h1></header>{children}</div>};function Filters({q,setQ,active,setActive}){return <div className="tkb-controls"><input className="tkb-search" placeholder="Tìm kiếm" value={q} onChange={e=>setQ(e.target.value)}/><select value={active} onChange={e=>setActive(e.target.value)}><option value="all">Tất cả trạng thái</option><option value="true">Active</option><option value="false">Inactive</option></select></div>};function Table({heads,rows}){return <div className="tkb-grid-wrap"><table className="tkb-grid"><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.length?rows:<tr><td colSpan={heads.length}>Không có dữ liệu.</td></tr>}</tbody></table></div>};function Info({rows}){return <dl className="tkb-metrics">{rows.map(([k,v])=><div className="tkb-metric" key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>};function labelSession(v){return ({morning:'Sáng',afternoon:'Chiều',both:'Cả hai'})[v]??'—'};
