'use strict';
const express = require('express');
const auth = require('../../middlewares/auth.middleware');
const { requirePermission } = require('../../middlewares/rbac.middleware');
const controller = require('./presentation.controller');
const { PERMISSIONS } = require('../../shared/permissions');
const router = express.Router();
router.get('/canva/callback', controller.callback);
router.use(auth);
router.get('/canva/connect', requirePermission(PERMISSIONS.PRESENTATION_CREATE), controller.connect);
router.get('/canva/status', requirePermission(PERMISSIONS.PRESENTATION_VIEW), controller.connectionStatus);
router.get('/', requirePermission(PERMISSIONS.PRESENTATION_VIEW), controller.list);
router.post('/', requirePermission(PERMISSIONS.PRESENTATION_CREATE), controller.create);
router.get('/:id', requirePermission(PERMISSIONS.PRESENTATION_VIEW), controller.detail);
router.patch('/:id', requirePermission(PERMISSIONS.PRESENTATION_UPDATE), controller.update);
router.post('/:id/canva', requirePermission(PERMISSIONS.PRESENTATION_CREATE), controller.createCanva);
router.post('/:id/export', requirePermission(PERMISSIONS.PRESENTATION_EXPORT), controller.exportFile);
router.post('/:id/pptx', requirePermission(PERMISSIONS.PRESENTATION_VIEW, PERMISSIONS.PRESENTATION_EXPORT), controller.downloadPptx);
router.get('/:id/media', requirePermission(PERMISSIONS.PRESENTATION_VIEW), controller.listMedia);
router.post('/:id/media-plan', requirePermission(PERMISSIONS.PRESENTATION_VIEW, PERMISSIONS.PRESENTATION_CREATE), controller.suggestMedia);
router.post('/:id/media', requirePermission(PERMISSIONS.PRESENTATION_VIEW, PERMISSIONS.PRESENTATION_CREATE), controller.createMedia);
router.post('/:id/media/:assetId/refresh', requirePermission(PERMISSIONS.PRESENTATION_VIEW), controller.refreshMedia);
router.get('/:id/media/:assetId/content', requirePermission(PERMISSIONS.PRESENTATION_VIEW), controller.mediaContent);
router.delete('/:id', requirePermission(PERMISSIONS.PRESENTATION_DELETE), controller.remove);
module.exports = router;
