'use strict';
const crypto = require('node:crypto');
const env = require('../../config');
const ApiError = require('../../shared/ApiError');
const { getPresentationModel } = require('./presentation.model');
const memoryOauth = new Map();
const userTokens = new Map();
function tokenKey() { if (!env.PRESENTATION.TOKEN_ENCRYPTION_KEY) throw new Error('PRESENTATION_TOKEN_ENCRYPTION_KEY is not configured.'); return Buffer.from(env.PRESENTATION.TOKEN_ENCRYPTION_KEY, 'hex'); }
function encryptToken(value) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', tokenKey(), iv); const encrypted = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${encrypted.toString('base64url')}`; }
function decryptToken(value) { const [iv, tag, encrypted] = String(value).split('.').map((part) => Buffer.from(part, 'base64url')); const decipher = crypto.createDecipheriv('aes-256-gcm', tokenKey(), iv); decipher.setAuthTag(tag); return Buffer.concat([decipher.update(encrypted), decipher.final()]).toString('utf8'); }
function ownerFilter(id) { return { ownerId: id }; }
function authConfigured() { return !!(env.PRESENTATION.CANVA.CLIENT_ID && env.PRESENTATION.CANVA.CLIENT_SECRET && env.PRESENTATION.CANVA.REDIRECT_URI); }
function canvaHeaders(token, json = false) { return { Authorization: `Bearer ${token}`, ...(json ? { 'Content-Type': 'application/json' } : {}) }; }
async function modelRequest(prompt) {
  if (!env.PRESENTATION.MODEL_API_URL || !env.PRESENTATION.MODEL_API_KEY || !env.PRESENTATION.MODEL_API_MODEL) throw ApiError.serviceUnavailable?.('ModelAPI chưa được cấu hình.') || new ApiError(503, 'ModelAPI chưa được cấu hình.');
  const response = await fetch(env.PRESENTATION.MODEL_API_URL, { method: 'POST', headers: { Authorization: `Bearer ${env.PRESENTATION.MODEL_API_KEY}`, 'Content-Type': 'application/json' }, signal: AbortSignal.timeout(30000), body: JSON.stringify({ model: env.PRESENTATION.MODEL_API_MODEL, messages: [{ role: 'user', content: prompt }] }) });
  if (!response.ok) throw new Error(`ModelAPI HTTP ${response.status}`);
  const data = await response.json(); const raw = data.output_text || data.output?.flatMap((x) => x.content || []).find((x) => x.type === 'output_text')?.text || data.choices?.[0]?.message?.content;
  try { return JSON.parse(raw); } catch { throw new Error('ModelAPI không trả về JSON cấu trúc slide hợp lệ.'); }
}
async function outline(ownerId, input) {
  const model = await getPresentationModel(); const row = await model.create({ ...input, ...ownerFilter(ownerId), status: 'generating_outline' });
  try { const result = await modelRequest(`Tạo cấu trúc bài thuyết trình bằng ${input.language}. Chỉ trả JSON {slides:[{title,content,notes}]}, đúng ${input.slideCount} slide. Không bịa số liệu hoặc nguồn. Tiêu đề: ${input.title}\nĐối tượng: ${input.audience}\nPhong cách: ${input.style}\nNguồn:\n${input.sourceContent}`); const slides = result.slides; if (!Array.isArray(slides) || slides.length !== input.slideCount) throw new Error('ModelAPI trả về số slide không đúng.'); row.outline = slides; row.status = 'ready'; await row.save(); return row.toObject(); } catch (error) { row.status = 'failed'; row.error = error.message; await row.save(); throw error; }
}
async function getOwned(ownerId, id) { const model = await getPresentationModel(); const row = await model.findOne({ _id: id, ...ownerFilter(ownerId) }); if (!row) throw ApiError.notFound('Không tìm thấy bài thuyết trình hoặc bạn không có quyền truy cập.'); return row; }
async function list(ownerId) { const model = await getPresentationModel(); return model.find(ownerFilter(ownerId)).sort({ createdAt: -1 }).select('-canvaRefreshToken').lean(); }
async function update(ownerId, id, values) { const row = await getOwned(ownerId, id); if (row.status === 'creating' || row.status === 'completed') throw ApiError.conflict('Bài thuyết trình đã được gửi tới Canva và không thể sửa cấu trúc.'); Object.assign(row, values, { status: 'ready', error: '' }); await row.save(); return row.toObject(); }
function oauthStart(userId) { if (!authConfigured()) throw ApiError.serviceUnavailable?.('Canva OAuth chưa được cấu hình.') || new ApiError(503, 'Canva OAuth chưa được cấu hình.'); const verifier = crypto.randomBytes(64).toString('base64url'); const state = crypto.randomBytes(48).toString('base64url'); const challenge = crypto.createHash('sha256').update(verifier).digest('base64url'); memoryOauth.set(state, { userId, verifier, expiresAt: Date.now() + 10 * 60 * 1000 }); const params = new URLSearchParams({ code_challenge: challenge, code_challenge_method: 'S256', scope: env.PRESENTATION.CANVA.SCOPES, response_type: 'code', client_id: env.PRESENTATION.CANVA.CLIENT_ID, state, redirect_uri: env.PRESENTATION.CANVA.REDIRECT_URI }); return `https://www.canva.com/api/oauth/authorize?${params}`; }
async function oauthCallback(code, state) { const saved = memoryOauth.get(state); memoryOauth.delete(state); if (!saved || saved.expiresAt < Date.now()) throw ApiError.badRequest('Phiên kết nối Canva đã hết hạn.'); const credentials = Buffer.from(`${env.PRESENTATION.CANVA.CLIENT_ID}:${env.PRESENTATION.CANVA.CLIENT_SECRET}`).toString('base64'); const response = await fetch('https://api.canva.com/rest/v1/oauth/token', { method: 'POST', headers: { Authorization: `Basic ${credentials}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'authorization_code', code_verifier: saved.verifier, code, redirect_uri: env.PRESENTATION.CANVA.REDIRECT_URI }) }); if (!response.ok) throw new Error(`Canva OAuth HTTP ${response.status}`); const token = await response.json(); userTokens.set(saved.userId, token.refresh_token); const model = await getPresentationModel(); await model.updateMany(ownerFilter(saved.userId), { $set: { canvaRefreshToken: encryptToken(token.refresh_token), canvaTokenExpiresAt: new Date(Date.now() + (token.expires_in || 14400) * 1000) } }); return saved.userId; }
async function accessToken(row) { const refresh = row.canvaRefreshToken ? decryptToken(row.canvaRefreshToken) : userTokens.get(String(row.ownerId)); if (!refresh) throw ApiError.serviceUnavailable?.('Chưa kết nối tài khoản Canva.') || new Error('Chưa kết nối tài khoản Canva.'); const credentials = Buffer.from(`${env.PRESENTATION.CANVA.CLIENT_ID}:${env.PRESENTATION.CANVA.CLIENT_SECRET}`).toString('base64'); const response = await fetch('https://api.canva.com/rest/v1/oauth/token', { method: 'POST', headers: { Authorization: `Basic ${credentials}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'refresh_token', refresh_token: refresh }) }); if (!response.ok) throw new Error(`Canva token refresh HTTP ${response.status}`); const token = await response.json(); const nextRefresh = token.refresh_token || refresh; userTokens.set(String(row.ownerId), nextRefresh); row.canvaRefreshToken = encryptToken(nextRefresh); row.canvaTokenExpiresAt = new Date(Date.now() + (token.expires_in || 14400) * 1000); await row.save(); return token.access_token; }
async function createOnCanva(ownerId, id, idempotencyKey) { const row = await getOwned(ownerId, id); if (row.status === 'creating') return row.toObject(); if (row.status === 'completed') return row.toObject(); if (!['ready','failed'].includes(row.status)) throw ApiError.conflict('Bài thuyết trình chưa có cấu trúc hợp lệ.'); if (idempotencyKey && row.createIdempotencyKey === idempotencyKey && row.status === 'creating') return row.toObject(); row.status = 'creating'; row.error = ''; row.createIdempotencyKey = idempotencyKey || crypto.randomUUID(); await row.save(); try { const token = await accessToken(row); const response = await fetch('https://api.canva.com/rest/v1/generations', { method: 'POST', headers: canvaHeaders(token, true), body: JSON.stringify({ brief: `${row.title}. Ngôn ngữ: ${row.language}. Đối tượng: ${row.audience}. Phong cách: ${row.style}. Nội dung nguồn:\n${row.sourceContent}`, design_type: { type: 'preset', name: 'presentation' }, outline: { sections: row.outline.map((s) => ({ title: s.title, description: s.content, points: [s.notes].filter(Boolean) })) } }) }); if (!response.ok) throw new Error(`Canva generation HTTP ${response.status}`); const payload = await response.json(); const job = payload.job || payload; row.canvaJobId = job.id; await row.save(); return pollCanva(row); } catch (error) { row.status = 'failed'; row.error = error.message; await row.save(); throw error; } }
async function pollCanva(row) { const token = await accessToken(row); const deadline = Date.now() + 120000; while (Date.now() < deadline) { const response = await fetch(`https://api.canva.com/rest/v1/generations/${row.canvaJobId}`, { headers: canvaHeaders(token) }); if (!response.ok) throw new Error(`Canva generation status HTTP ${response.status}`); const { job } = await response.json(); if (job.status === 'success') { row.status = 'completed'; row.canvaDesignId = job.result.design.id; row.canvaViewUrl = job.result.design.urls?.view_url; row.canvaEditUrl = job.result.design.urls?.edit_url; await row.save(); return row.toObject(); } if (job.status === 'failed') throw new Error(job.error?.message || 'Canva không tạo được thiết kế.'); await new Promise((resolve) => setTimeout(resolve, 3000)); } throw new Error('Canva generation timeout.'); }
async function exportDesign(ownerId, id, format) { const row = await getOwned(ownerId, id); if (row.status !== 'completed' || !row.canvaDesignId) throw ApiError.conflict('Thiết kế Canva chưa sẵn sàng để xuất.'); const token = await accessToken(row); const formats = await fetch(`https://api.canva.com/rest/v1/designs/${row.canvaDesignId}/export-formats`, { headers: canvaHeaders(token) }); if (!formats.ok) throw new Error(`Canva export formats HTTP ${formats.status}`); const available = (await formats.json()).formats || {}; if (!available[format]) throw ApiError.badRequest(`Canva không hỗ trợ xuất ${format.toUpperCase()} cho thiết kế này.`); const start = await fetch('https://api.canva.com/rest/v1/exports', { method: 'POST', headers: canvaHeaders(token, true), body: JSON.stringify({ design_id: row.canvaDesignId, format: { type: format } }) }); if (!start.ok) throw new Error(`Canva export HTTP ${start.status}`); const job = (await start.json()).job; const response = await fetch(`https://api.canva.com/rest/v1/exports/${job.id}`, { headers: canvaHeaders(token) }); if (!response.ok) throw new Error(`Canva export status HTTP ${response.status}`); const done = await response.json(); if (done.job?.status === 'success') { if (!row.exportUrls) row.exportUrls = new Map(); row.exportUrls.set(format, done.job.urls?.[0]); await row.save(); return row.toObject(); } return { ...row.toObject(), exportPending: true, exportJobId: job.id };
}
module.exports = { outline, list, getOwned, update, oauthStart, oauthCallback, createOnCanva, exportDesign };
