import { useEffect, useState } from 'react';
import { presentationApi, errorMessage } from '../service';
import { usePermission } from '../../auth/hooks';
import { PERMISSIONS } from '../../../lib/env';
import { Input, Textarea, Select } from '../../../components/ui/Input';
import Button from '../../../components/ui/Button';
import Icon from '../../../components/ui/Icon';
import { Modal } from '../../../components/ui/Modal';
import './PresentationsPage.css';

const empty = { title:'', sourceContent:'', language:'Tiếng Việt', audience:'', slideCount:6, style:'Dark SaaS hiện đại' };
const statusText = { ready:'Đã sẵn sàng', creating:'Đang tạo trên Canva', completed:'Đã tạo', failed:'Lỗi' };
export default function PresentationsPage() {
  const [form,setForm]=useState(empty), [rows,setRows]=useState([]), [selected,setSelected]=useState(null), [busy,setBusy]=useState(false), [error,setError]=useState(''), [confirmOpen,setConfirmOpen]=useState(false);
  const perm=usePermission(); const canCreate=perm.hasAll([PERMISSIONS.PRESENTATION_CREATE]);
  const load=async()=>{try{setRows(await presentationApi.list())}catch(e){setError(errorMessage(e))}}; useEffect(()=>{load()},[]);
  const set=(k,v)=>setForm(x=>({...x,[k]:v}));
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{setSelected(await presentationApi.createOutline({...form,slideCount:Number(form.slideCount)}));await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  async function save(){setBusy(true);try{setSelected(await presentationApi.update(selected._id,{title:selected.title,outline:selected.outline}));await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  async function create(){setBusy(true);try{setSelected(await presentationApi.createCanva(selected._id,crypto.randomUUID()));await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  async function connect(){try{window.location.assign((await presentationApi.connectCanva()).authorizationUrl)}catch(e){setError(errorMessage(e))}}
  return <main className="gp-page presentation-page"><header className="presentation-hero"><div><span className="presentation-kicker">CANVA STUDIO</span><h1 className="gp-h1">Tạo bài thuyết trình</h1><p className="gp-muted">Từ nội dung nguồn đến thiết kế Canva có thể chỉnh sửa.</p></div><Button variant="ghost" onClick={connect} icon={<Icon name="spark" size={15}/>}>Kết nối Canva</Button></header><div className="presentation-steps"><b>01 Nhập nội dung</b><i/> <b className={selected?'active':''}>02 Sửa cấu trúc</b><i/> <b className={selected?.status==='completed'?'active':''}>03 Kết quả</b></div>{error&&<div className="presentation-alert" role="alert">{error}</div>}
  {!selected&&<form className="presentation-grid" onSubmit={submit}><section className="presentation-card"><div className="card-heading"><div><span className="eyebrow">Nguồn nội dung</span><h2>Thông tin bài trình bày</h2></div><span className="step-badge">01</span></div><Input id="presentation-title" label="Tiêu đề" value={form.title} onChange={e=>set('title',e.target.value)} required placeholder="Ví dụ: Báo cáo chiến lược quý IV"/><Textarea id="presentation-source" label="Nội dung nguồn" value={form.sourceContent} onChange={e=>set('sourceContent',e.target.value)} required minLength={20} rows={12} placeholder="Dán nội dung, ghi chú hoặc tài liệu nguồn..."/><p className="source-note"><Icon name="info" size={15}/> Nội dung sẽ gửi tới ModelAPI để đề xuất cấu trúc, sau đó gửi tới Canva sau khi bạn xác nhận.</p></section><aside className="presentation-card"><div className="card-heading"><div><span className="eyebrow">Thiết lập</span><h2>Định hướng thiết kế</h2></div><span className="step-badge">02</span></div><Select id="presentation-language" label="Ngôn ngữ" value={form.language} onChange={e=>set('language',e.target.value)}><option>Tiếng Việt</option><option>English</option></Select><Input id="presentation-audience" label="Đối tượng người xem" value={form.audience} onChange={e=>set('audience',e.target.value)} required placeholder="Ví dụ: Ban giám đốc"/><Input id="presentation-count" label="Số slide" type="number" min="1" max="100" value={form.slideCount} onChange={e=>set('slideCount',e.target.value)} required/><Select id="presentation-style" label="Phong cách" value={form.style} onChange={e=>set('style',e.target.value)}><option>Dark SaaS hiện đại</option><option>Tối giản chuyên nghiệp</option><option>Năng động thương hiệu</option></Select><Button type="submit" fullWidth loading={busy} disabled={!canCreate}>Đề xuất cấu trúc <Icon name="arrow-right" size={15}/></Button></aside></form>}
  {selected&&selected.status!=='completed'&&<section className="presentation-card review-card"><div className="card-heading"><div><span className="eyebrow">Review outline</span><h2>Chỉnh sửa trước khi gửi Canva</h2></div><span className="step-badge">02</span></div><p className="review-meta"><b>{selected.title}</b> · {selected.slideCount} slide · {selected.audience}</p><div className="slide-list">{(selected.outline||[]).map((s,i)=><article className="slide-editor" key={i}><div className="slide-number">{String(i+1).padStart(2,'0')}</div><div className="slide-fields"><Input label="Tiêu đề slide" value={s.title} onChange={e=>setSelected(r=>({...r,outline:r.outline.map((x,j)=>j===i?{...x,title:e.target.value}:x)}))}/><Textarea label="Nội dung" rows={3} value={s.content} onChange={e=>setSelected(r=>({...r,outline:r.outline.map((x,j)=>j===i?{...x,content:e.target.value}:x)}))}/><Textarea label="Ghi chú" rows={2} value={s.notes||''} onChange={e=>setSelected(r=>({...r,outline:r.outline.map((x,j)=>j===i?{...x,notes:e.target.value}:x)}))}/></div></article>)}</div><div className="review-actions"><Button variant="ghost" onClick={()=>setSelected(null)}>Tạo bản khác</Button><Button onClick={save} loading={busy}>Lưu cấu trúc</Button><Button variant="accent" onClick={()=>setConfirmOpen(true)} loading={busy}>Xác nhận tạo Canva</Button></div><Modal open={confirmOpen} title="Xác nhận gửi tới Canva" onClose={()=>setConfirmOpen(false)} busy={busy} footer={<><Button variant="ghost" onClick={()=>setConfirmOpen(false)}>Hủy</Button><Button variant="accent" onClick={()=>{setConfirmOpen(false);create()}} loading={busy}>Gửi và tạo thiết kế</Button></>}><p className="gp-muted">Canva sẽ nhận tiêu đề, ngôn ngữ, đối tượng, phong cách và outline {selected.outline.length} slide dưới đây.</p><ul>{selected.outline.slice(0,3).map((s,i)=><li key={i}><b>{i+1}. {s.title}</b> — {s.content}</li>)}{selected.outline.length>3&&<li>… và {selected.outline.length-3} slide khác</li>}</ul></Modal></section>}
  {selected&&selected.status==='completed'&&<section className="presentation-card result-card"><div className="result-icon"><Icon name="check" size={24}/></div><span className="eyebrow">{statusText[selected.status]}</span><h2>{selected.title}</h2><p className="gp-muted">Canva đã trả về thiết kế thật.</p><div className="result-links"><a href={selected.canvaViewUrl} target="_blank" rel="noreferrer">Mở bản xem</a><a href={selected.canvaEditUrl} target="_blank" rel="noreferrer">Mở chỉnh sửa</a></div><Button variant="ghost" onClick={()=>setSelected(null)}>Tạo bài khác</Button></section>}
  <section className="presentation-history"><div className="card-heading"><div><span className="eyebrow">Workspace</span><h2>Lịch sử thiết kế</h2></div></div>{rows.length?<div className="history-list">{rows.map(r=><button className="history-row" key={r._id} onClick={()=>setSelected(r)}><span><b>{r.title}</b><small>{new Date(r.createdAt).toLocaleString('vi-VN')}</small></span><em>{statusText[r.status]||r.status}</em></button>)}</div>:<p className="gp-muted">Chưa có bài thuyết trình nào.</p>}</section></main>;
}
