import CanvaConnectionBanner from '../components/CanvaConnectionBanner';
import SlideMediaPanel from '../components/SlideMediaPanel';
import DesignHistory from '../components/DesignHistory';
import { useEffect, useState } from 'react';
import { presentationApi, errorMessage } from '../service';
import { usePermission } from '../../auth/hooks';
import { PERMISSIONS } from '../../../lib/env';
import { Input, Textarea, Select } from '../../../components/ui/Input';
import Button from '../../../components/ui/Button';
import Icon from '../../../components/ui/Icon';
import { Modal } from '../../../components/ui/Modal';
import { useTopbar } from '../../../layouts/AdminLayout';
import './PresentationsPage.css';

const empty = { title:'', sourceContent:'', language:'Tiếng Việt', audience:'', slideCount:6, style:'Năng động thương hiệu', visualStyle:'Flat Design & Illustration', presentationType:'Education' };
const statusText = { ready:'Đã sẵn sàng', creating:'Đang tạo trên Canva', completed:'Đã tạo', failed:'Lỗi' };
const previewThemes = {
  'Dark SaaS hiện đại': { bg:'#101b30', accent:'#72e8ff', secondary:'#b7a7ff', text:'#f8fafc' },
  'Tối giản chuyên nghiệp': { bg:'#f7f8fc', accent:'#2457a6', secondary:'#247c76', text:'#172033' },
  'Năng động thương hiệu': { bg:'#fff0e8', accent:'#f05d5e', secondary:'#7b3fe4', text:'#30203f' },
};
const visualStyleLabels={'Minimalism':'Tối giản','Flat Design & Illustration':'Thiết kế phẳng và minh họa','Glassmorphism':'Kính mờ','Editorial':'Tạp chí','Monochrome & Muted':'Đơn sắc và màu trầm','Bold Geometric / Poster':'Hình học táo bạo','Tech Wireframe':'Công nghệ đường nét'};
const presentationTypeLabels={'Corporate & Business':'Doanh nghiệp','Education':'Giáo dục','Minigame / Event':'Trò chơi / Sự kiện','Văn hóa & Truyền thống':'Văn hóa & Truyền thống'};
function DesignPreview({visualStyle,style,presentationType}) {
  const theme=previewThemes[style]||previewThemes['Dark SaaS hiện đại'];
  const isPoster=visualStyle==='Bold Geometric / Poster', isWire=visualStyle==='Tech Wireframe', isGlass=visualStyle==='Glassmorphism', isEditorial=visualStyle==='Editorial', isMono=visualStyle==='Monochrome & Muted';
  const className=isPoster?'poster':isWire?'wire':isGlass?'glass':isEditorial?'editorial':isMono?'mono':visualStyle==='Minimalism'?'minimal':'flat';
  const cssVars={'--preview-bg':isPoster?'#0a0a0b':isWire?'#201b75':theme.bg,'--preview-accent':isPoster?'#ff641e':isWire?'#21c4d6':theme.accent,'--preview-secondary':isWire?'#45e0c2':theme.secondary,'--preview-text':isPoster?'#fff3de':isWire?'#f4f7ff':theme.text};
  const title=isPoster?'BẬT CHẤT RIÊNG':isWire?'MERIDIAN':isEditorial?'Một câu chuyện rõ ràng':'MỘT Ý CHÍNH';
  return <div className={`design-preview design-preview--${className}`} style={cssVars}><div className="preview-curve preview-curve--one"/><div className="preview-curve preview-curve--two"/><div className="preview-blob"/><div className="preview-glass"/><div className="preview-copy"><small>{presentationTypeLabels[presentationType]||presentationType}</small><b>{title}</b><span>{visualStyleLabels[visualStyle]||visualStyle}</span><em>Ảnh và nội dung theo vai trò từng trang</em></div><div className="preview-modules" aria-hidden><i/><i/><i/></div><div className="preview-editorial-media" aria-hidden/><div className="preview-mono-band" aria-hidden><i/><i/><i/></div></div>;
}
export default function PresentationsPage() {
  const [form,setForm]=useState(empty), [rows,setRows]=useState([]), [selected,setSelected]=useState(null), [busy,setBusy]=useState(false), [error,setError]=useState(''), [confirmOpen,setConfirmOpen]=useState(false);
  const [mediaIds,setMediaIds]=useState([]), [mediaPending,setMediaPending]=useState(false);
  useEffect(()=>{setMediaIds([]);setMediaPending(false);},[selected?._id]);
  const [canva,setCanva]=useState({configured:false,connected:false,loading:true});
  const {set:setTopbar}=useTopbar();
  useEffect(()=>{setTopbar({title:'Bài thuyết trình',subtitle:'Soạn nội dung và xuất bản trình chiếu',breadcrumbs:[{label:'Tổng quan',path:'/dashboard'},{label:'Bài thuyết trình'}]});return()=>setTopbar({title:'',subtitle:'',breadcrumbs:[]})},[setTopbar]);
  const perm=usePermission(); const canCreate=perm.hasAll([PERMISSIONS.PRESENTATION_CREATE]);
  const load=async()=>{try{const [list,status]=await Promise.all([presentationApi.list(),presentationApi.connectionStatus()]);setRows(list);setCanva({...status,loading:false})}catch(e){setError(errorMessage(e))}}; useEffect(()=>{load()},[]);
  async function downloadPptx(){setBusy(true);setError('');try{const blob=await presentationApi.downloadPptx(selected._id,selected.outline,mediaIds);const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=(selected.title||'presentation').replace(/[\\/:*?"<>|]/g,'-')+'.pptx';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  const set=(k,v)=>setForm(x=>({...x,[k]:v}));
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{setSelected(await presentationApi.createOutline({...form,slideCount:Number(form.slideCount)}));await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  async function save(){setBusy(true);try{setSelected(await presentationApi.update(selected._id,{title:selected.title,outline:selected.outline}));await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  async function create(){setBusy(true);try{setSelected(await presentationApi.createCanva(selected._id,crypto.randomUUID()));await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  async function connect(){try{window.location.assign((await presentationApi.connectCanva()).authorizationUrl)}catch(e){setError(errorMessage(e))}}
  function historyDeleted(id){setRows(current=>current.filter(row=>row._id!==id));setSelected(current=>current?._id===id?null:current)}
  const connectionBanner = <CanvaConnectionBanner status={canva} onConnect={connect} canConnect={canCreate} />;
  return <main className="gp-page presentation-page"><header className="presentation-hero"><div><span className="presentation-kicker">TRÌNH CHIẾU GIA PHÚC</span><h1 className="gp-h1">Tạo bài thuyết trình</h1><p className="gp-muted">Soạn nội dung bằng AI, tải PowerPoint trực tiếp hoặc tạo thiết kế Canva.</p></div><Button variant="ghost" onClick={connect} icon={<Icon name="spark" size={15}/>}>Kết nối Canva</Button></header>{connectionBanner}<div className="presentation-steps"><b>01 Nhập nội dung</b><i/> <b className={selected?'active':''}>02 Sửa cấu trúc</b><i/> <b className={selected?.status==='completed'?'active':''}>03 Kết quả</b></div>{error&&<div className="presentation-alert" role="alert">{error}</div>}
  {!selected&&<form className="presentation-grid" onSubmit={submit}><section className="presentation-card"><div className="card-heading"><div><span className="eyebrow">Nguồn nội dung</span><h2>Thông tin bài trình bày</h2></div><span className="step-badge">01</span></div><Input id="presentation-title" label="Tiêu đề" value={form.title} onChange={e=>set('title',e.target.value)} required placeholder="Ví dụ: Báo cáo chiến lược quý IV"/><Textarea id="presentation-source" label="Nội dung nguồn" value={form.sourceContent} onChange={e=>set('sourceContent',e.target.value)} required minLength={20} rows={12} placeholder="Dán nội dung, ghi chú hoặc tài liệu nguồn..."/><p className="source-note"><Icon name="info" size={15}/> Nội dung sẽ gửi tới ModelAPI để đề xuất cấu trúc, sau đó gửi tới Canva sau khi bạn xác nhận.</p></section><aside className="presentation-card"><div className="card-heading"><div><span className="eyebrow">Thiết lập</span><h2>Định hướng thiết kế</h2></div><span className="step-badge">02</span></div><Select id="presentation-language" label="Ngôn ngữ" value={form.language} onChange={e=>set('language',e.target.value)}><option>Tiếng Việt</option><option value="English">Tiếng Anh</option></Select><Input id="presentation-audience" label="Đối tượng người xem" value={form.audience} onChange={e=>set('audience',e.target.value)} required placeholder="Ví dụ: Ban giám đốc"/><Input id="presentation-count" label="Số trang" type="number" min="1" max="100" value={form.slideCount} onChange={e=>set('slideCount',e.target.value)} required/><Select id="presentation-type" label="Loại nội dung" value={form.presentationType} onChange={e=>set('presentationType',e.target.value)}><option value="Corporate & Business">Doanh nghiệp</option><option value="Education">Giáo dục</option><option value="Minigame / Event">Trò chơi / Sự kiện</option><option>Văn hóa &amp; Truyền thống</option></Select><Select id="presentation-visual-style" label="Phong cách thị giác" value={form.visualStyle} onChange={e=>set('visualStyle',e.target.value)}><option value="Minimalism">Tối giản</option><option value="Flat Design & Illustration">Thiết kế phẳng và minh họa</option><option value="Glassmorphism">Kính mờ</option><option value="Editorial">Tạp chí</option><option value="Monochrome & Muted">Đơn sắc và màu trầm</option><option value="Bold Geometric / Poster">Hình học táo bạo</option><option value="Tech Wireframe">Công nghệ đường nét</option></Select><Select id="presentation-style" label="Hệ màu" value={form.style} onChange={e=>set('style',e.target.value)}><option value="Dark SaaS hiện đại">Công nghệ tối hiện đại</option><option>Tối giản chuyên nghiệp</option><option>Năng động thương hiệu</option></Select><DesignPreview visualStyle={form.visualStyle} style={form.style} presentationType={form.presentationType}/><Button type="submit" fullWidth loading={busy} disabled={!canCreate}>Đề xuất cấu trúc <Icon name="arrow-right" size={15}/></Button></aside></form>}
  {selected&&selected.status!=='completed'&&<section className="presentation-card review-card"><div className="card-heading"><div><span className="eyebrow">DUYỆT DÀN Ý</span><h2>Chỉnh sửa trước khi gửi Canva</h2></div><span className="step-badge">02</span></div><p className="review-meta"><b>{selected.title}</b> · {selected.slideCount} trang · {selected.audience}</p><div className="slide-list">{(selected.outline||[]).map((s,i)=><article className="slide-editor" key={i}><div className="slide-number">{String(i+1).padStart(2,'0')}</div><div className="slide-fields"><Input label="Tiêu đề slide" value={s.title} onChange={e=>setSelected(r=>({...r,outline:r.outline.map((x,j)=>j===i?{...x,title:e.target.value}:x)}))}/><Textarea label="Nội dung" rows={3} value={s.content} onChange={e=>setSelected(r=>({...r,outline:r.outline.map((x,j)=>j===i?{...x,content:e.target.value}:x)}))}/><Textarea label="Ghi chú" rows={2} value={s.notes||''} onChange={e=>setSelected(r=>({...r,outline:r.outline.map((x,j)=>j===i?{...x,notes:e.target.value}:x)}))}/></div></article>)}</div><div className="review-actions"><Button variant="ghost" onClick={()=>setSelected(null)}>Tạo bản khác</Button><Button onClick={save} loading={busy}>Lưu cấu trúc</Button><Button variant="accent" onClick={()=>setConfirmOpen(true)} disabled={canva.loading || !canva.connected || !canCreate} loading={busy}>Xác nhận tạo Canva</Button></div><Modal open={confirmOpen} title="Xác nhận gửi tới Canva" onClose={()=>setConfirmOpen(false)} busy={busy} footer={<><Button variant="ghost" onClick={()=>setConfirmOpen(false)}>Hủy</Button><Button variant="accent" onClick={()=>{setConfirmOpen(false);create()}} disabled={!canva.connected || !canCreate} loading={busy}>Gửi và tạo thiết kế</Button></>}><p className="gp-muted">Canva sẽ nhận tiêu đề, ngôn ngữ, đối tượng, phong cách và dàn ý {selected.outline.length} trang dưới đây.</p><ul>{selected.outline.slice(0,3).map((s,i)=><li key={i}><b>{i+1}. {s.title}</b> — {s.content}</li>)}{selected.outline.length>3&&<li>… và {selected.outline.length-3} trang khác</li>}</ul></Modal></section>}
  {selected&&selected.outline?.length>0&&<><SlideMediaPanel key={selected._id} presentation={selected} canCreate={canCreate} onSelectionChange={setMediaIds} onPendingChange={setMediaPending}/><section className="presentation-direct-export"><div><strong>PowerPoint trực tiếp</strong><p>Đính kèm {mediaIds.length} minh họa đã xem trước. Nội dung và ghi chú có thể chỉnh sửa trong PowerPoint. Không cần kết nối Canva.</p>{mediaPending&&<p role="status">Đang tạo minh họa. Chờ hoàn tất hoặc tắt minh họa để tải bản chỉ có nội dung.</p>}</div><Button onClick={downloadPptx} loading={busy} disabled={mediaPending||!perm.hasAll([PERMISSIONS.PRESENTATION_EXPORT])}>Tải PowerPoint (.pptx)</Button></section></>}
  {selected&&selected.status==='completed'&&<section className="presentation-card result-card"><div className="result-icon"><Icon name="check" size={24}/></div><span className="eyebrow">{statusText[selected.status]}</span><h2>{selected.title}</h2><p className="gp-muted">Canva đã trả về thiết kế thật.</p><div className="result-links"><a href={selected.canvaViewUrl} target="_blank" rel="noreferrer">Mở bản xem</a><a href={selected.canvaEditUrl} target="_blank" rel="noreferrer">Mở chỉnh sửa</a></div><Button variant="ghost" onClick={()=>setSelected(null)}>Tạo bài khác</Button></section>}
  <DesignHistory rows={rows} onOpen={setSelected} onDeleted={historyDeleted}/></main>;
}
